### ISSUE TITLE
Cannot start collector on fresh install (XStream could not load the collector's config file)

### ISSUE THREAD

**Issue by jonesbusy** [denkbar/djigger#137]
Hello,

It's not possible to start the collector (release 1.11.3) on Windows (msys2 environment) 

We receive following exception

```
A fatal error occurred while starting collector.
java.lang.RuntimeException: XStream could not load the collector's config file located at C:/Users/delayev/AppData/Local/Programs/msys2/home/delayev/Download/djigger/conf/Collector.xml. Exception message was : io.djigger.collector.server.conf.CollectorConfig
        at io.djigger.collector.server.conf.Configurator.parseCollectorConfiguration(Configurator.java:64)
        at io.djigger.collector.server.Server.start(Server.java:72)
        at io.djigger.collector.server.Server.main(Server.java:52)
Caused by: com.thoughtworks.xstream.security.ForbiddenClassException: io.djigger.collector.server.conf.CollectorConfig
        at com.thoughtworks.xstream.security.NoTypePermission.allows(NoTypePermission.java:26)
        at com.thoughtworks.xstream.mapper.SecurityMapper.realClass(SecurityMapper.java:74)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
        at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:47)
        at com.thoughtworks.xstream.core.util.HierarchicalStreams.readClassType(HierarchicalStreams.java:29)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:133)
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1391)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1376)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1342)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1292)
        at io.djigger.collector.server.conf.Configurator.parseCollectorConfiguration(Configurator.java:60)
        ... 2 common frames omitted
```

The following collector file exists and is readable `cat ../conf/Collector.xml`

```
<Collector>
        <servicePort>8080</servicePort>
        <dataTTL>86400</dataTTL>
        <db host="localhost"/>
        <connectionFiles>
                <string>conf/Connections.json</string>
                <!-- Uncomment the following if you wan't to use the CSV configuration format -->
                <!-- <connectionFiles><string>conf/Connections.csv</string></connectionFiles> -->
                <!-- Uncomment the following if you wan't to use the XML configuration format -->
                <!-- <string>conf/Connections.xml</string> -->
        </connectionFiles>
</Collector>
```

Java version

```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

To reproduce 

```
wget https://github.com/exense/djigger/releases/download/1.11.3/djigger-1.11.3.zip
unzip djigger-1.11.3.zip
cd bin
./startCollector.sh
```

Thanks for your tips

PS : Didn't try yet on Linux, but need to test before on my machine (to implement Ansible playbook to deploy and configure the collector)

**Comment by jonesbusy** [comment]
Confirmed working with 1.11.4. Thanks
