### ISSUE TITLE
[Client/Agent] Instrumented method does not produce statistic, has exception

### ISSUE THREAD

**Issue by dcransac** [denkbar/djigger#37]
```
Starting agent. Arguments: port:12987
Adding C:\Users\---\AppData\Local\Temp\collector-b093fd48-d6b7-4338-aea3-0166955ec8441104593221160036510.jar to bootstrap search.
Agent: starting server socket on port 12987
Sent dumps in: 32
Sent dumps in: 6
Sent dumps in: 1
Sent dumps in: 0
Sent dumps in: 1
Sent dumps in: 1
Sent dumps in: 0
Sent dumps in: 9
Sent dumps in: 0
Sent dumps in: 1
Sent dumps in: 0
Sent dumps in: 2
Sent dumps in: 0
Sent dumps in: 0
Sent dumps in: 2
Sent dumps in: 0
Sent dumps in: 0
Sent dumps in: 0
Redefining io.djigger.ui.MainToolbarPane
Appending classpath: sun.misc.Launcher$AppClassLoader@14dad5dc
java.lang.RuntimeException: java.io.IOException: invalid constant type: 15
	at javassist.CtClassType.getClassFile2(CtClassType.java:203)
	at javassist.CtClassType.makeFieldCache(CtClassType.java:837)
	at javassist.CtClassType.getMembers(CtClassType.java:828)
	at javassist.CtClassType.getDeclaredField2(CtClassType.java:950)
	at javassist.CtClassType.getField2(CtClassType.java:905)
	at javassist.CtClassType.getField2(CtClassType.java:920)
	at javassist.CtClassType.getField2(CtClassType.java:920)
	at javassist.CtClassType.getField(CtClassType.java:897)
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:804)
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:770)
	at javassist.compiler.TypeChecker.atMember(TypeChecker.java:952)
	at javassist.compiler.JvstTypeChecker.atMember(JvstTypeChecker.java:65)
	at javassist.compiler.ast.Member.accept(Member.java:38)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:653)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:156)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:45)
	at javassist.compiler.TypeChecker.atVariableAssign(TypeChecker.java:248)
	at javassist.compiler.TypeChecker.atAssignExpr(TypeChecker.java:217)
	at javassist.compiler.ast.AssignExpr.accept(AssignExpr.java:38)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:241)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:329)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:49)
	at javassist.compiler.Javac.compileStmnt(Javac.java:568)
	at javassist.CtBehavior.insertBefore(CtBehavior.java:705)
	at javassist.CtBehavior.insertBefore(CtBehavior.java:685)
	at io.djigger.agent.ClassTransformer.transform(ClassTransformer.java:86)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at io.djigger.agent.InstrumentationService.applySubscriptionChange(InstrumentationService.java:74)
	at io.djigger.agent.InstrumentationService.addSubscription(InstrumentationService.java:55)
	at io.djigger.agent.AgentSession.onMessage(AgentSession.java:84)
	at org.smb.core.MessageRouter$CallListenerTask.run(MessageRouter.java:258)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: invalid constant type: 15
	at javassist.bytecode.ConstPool.readOne(ConstPool.java:1090)
	at javassist.bytecode.ConstPool.read(ConstPool.java:1033)
	at javassist.bytecode.ConstPool.<init>(ConstPool.java:149)
	at javassist.bytecode.ClassFile.read(ClassFile.java:737)
	at javassist.bytecode.ClassFile.<init>(ClassFile.java:108)
	at javassist.CtClassType.getClassFile2(CtClassType.java:190)
	... 38 more
Sent dumps in: 0
Sent dumps in: 0
Sent dumps in: 0
Sent dumps in: 0
Sent dumps in: 0
Sent dumps in: 0
Sent dumps in: 0
Sent dumps in: 3
Sent dumps in: 0
Sent dumps in: 0
Sent dumps in: 0

```

**Comment by jeromecomte** [comment]
Unable to reproduce it. Tested with oracle jdk1.8.0_77 and openjdk 1.7.0_95. which version are you using?

**Comment by dcransac** [comment]
Will check again on my local setup at home and see if I can reproduce and even build a reproduc_er_.

**Comment by dcransac** [comment]
Can't reproduce anymore with R1.4.2 (tested process attach, agent, in eclipse, without eclipse, etc).
