### ISSUE TITLE
[Client] Instrumentation : memory optimization

### ISSUE THREAD

**Issue by dcransac** [denkbar/djigger#46]
Instrumenting a method called often leads to very high memory consumption. In my mind, memory usage should be or nearly be independant from the frequency at which methods are called (see implementation of "InstrumentationSample" but probably more importantly (more surprising) the cardinality of StackTraceElement :

![image](https://cloud.githubusercontent.com/assets/5418782/14579192/5f48ada6-03a0-11e6-9eff-abf8b46e5839.png)

In my case, I was sampling at the default 1sec interval and just instrumented a java method which was called 3 million times. It pretty much killed the JVM (-> filled up approximately 2 GB Memory). Is there a way to optimize this?

![image](https://cloud.githubusercontent.com/assets/5418782/14579187/3a2d4734-03a0-11e6-8330-5f74188fad77.png)

**Comment by dcransac** [comment]
Exception in thread "Thread-4" java.lang.NegativeArraySizeException
	at io.djigger.monitoring.java.sampling.ThreadDumpHelper.toStackTraceElement(ThreadDumpHelper.java:47)
	at io.djigger.agent.Collector.report(Collector.java:54)
	at java.util.TreeMap.remove(TreeMap.java:609)
	at io.djigger.collector.test.BasicJMXJVM.iSleepUsingCPU(BasicJMXJVM.java:123)
	at io.djigger.collector.test.BasicJMXJVM.iWaste50pcOfTheTimeButIUseCPU(BasicJMXJVM.java:103)
	at io.djigger.collector.test.BasicJMXJVM.main(BasicJMXJVM.java:59)
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1537)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at java.util.ArrayList.writeObject(ArrayList.java:762)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at io.djigger.monitoring.java.sampling.ThreadDumpHelper.toStackTraceElement(ThreadDumpHelper.java:50)
	at io.djigger.agent.Collector.report(Collector.java:54)
	at java.util.TreeMap.remove(TreeMap.java:609)
	at io.djigger.collector.test.BasicJMXJVM.iSleepUsingCPU(BasicJMXJVM.java:127)
	at io.djigger.collector.test.BasicJMXJVM.iWaste50pcOfTheTimeButIUseCPU(BasicJMXJVM.java:103)
	at io.djigger.collector.test.BasicJMXJVM.main(BasicJMXJVM.java:59)

**Comment by dcransac** [comment]
High memory overhead on the target JVM's side as well. (see previous comment).
