### ISSUE TITLE
[Client] Process Attach fails with ClassCastException - High prio (for 1.5.2 / 1.6)

### ISSUE THREAD

**Issue by dcransac** [denkbar/djigger#80]
I'm using jdk1.8.0_73, as visible in my version of the start script down below.

PS: might want to also run a couple of tests with the delayed import of the tools.jar (using the system file open functionality).

Error :

```
D:\djigger-1.5.2\bin>"D:\Program Files\Java\jdk1.8.0_73\bin\java.exe" -Dlogback.configurationFile=logback-client.xml -cp "..\lib\*;D:\Program Files\Java\jdk1.8.0_73\bin\\..\lib\tools.jar" io.djigger.ui.MainFrame
    Starting agent. Arguments: host:nairod-PC,port:50915
Adding C:\Users\nairod\AppData\Local\Temp\collector-a35b46b1-fd82-45b6-b474-69571347d6f24369283972835323266.jar to bootstrap search.
Unexpected error
java.lang.ClassCastException: cannot assign instance of [Lio.djigger.monitoring.java.model.StackTraceElement; to field io.djigger.monitoring.java.model.ThreadInfo.stackTrace of type [Lio.djigger.monitoring.java.model.StackTraceElement; in instance of io.djigger.monitoring.java.model.ThreadInfo
        at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2133) ~[na:1.8.0_73]
        at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1305) ~[na:1.8.0_73]
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2006) ~[na:1.8.0_73]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924) ~[na:1.8.0_73]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_73]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_73]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371) ~[na:1.8.0_73]
        at java.util.LinkedList.readObject(LinkedList.java:1149) ~[na:1.8.0_73]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_73]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_73]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_73]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_73]
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058) ~[na:1.8.0_73]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1900) ~[na:1.8.0_73]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_73]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_73]
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000) ~[na:1.8.0_73]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924) ~[na:1.8.0_73]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_73]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_73]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371) ~[na:1.8.0_73]
        at org.smb.core.MessageRouter.run(MessageRouter.java:92) ~[smb-core-1.1.jar:na]
Unexpected error
java.io.EOFException: null
        at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2608) ~[na:1.8.0_73]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1319) ~[na:1.8.0_73]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371) ~[na:1.8.0_73]
        at org.smb.core.MessageRouter.run(MessageRouter.java:92) ~[smb-core-1.1.jar:na]
Agent: client disconnected.

```

Start script :

```
rem @echo off

rem if java.exe isn't on your path or is too old, then set your own as follows (watch for the backslash at the end):
rem SET JAVA_PATH=C:\Program Files\Java\jdk1.8.0_101\bin\
SET JAVA_PATH=D:\Program Files\Java\jdk1.8.0_73\bin\

SET JAVA_OPTS=-Dlogback.configurationFile=logback-client.xml

"%JAVA_PATH%java.exe" %JAVA_OPTS% -cp "..\lib\*;%JAVA_PATH%\..\lib\tools.jar" io.djigger.ui.MainFrame


```

**Comment by dcransac** [comment]
Perfect.
